### ISSUE TITLE
cannot import lib python 

### ISSUE THREAD

**Issue by zobi** [grm/py-smart-gardena#15]
hello i'm a noob but i cannot make a project with your lib :  
just make a py file with :

```
from gardena.smart_system import SmartSystem

smart_system = SmartSystem(email="email@gmail.com", password="my_password")
smart_system.authenticate()

```

result 

```

Traceback (most recent call last):
  File "gardena.py", line 1, in <module>
    from gardena.smart_system import SmartSystem
  File "/Dropbox/Domotique/gardena.py", line 1, in <module>
    from gardena.smart_system import SmartSystem
ModuleNotFoundError: No module named 'gardena.smart_system'; 'gardena' is not a package

```

i would like to implement your code in my smarthome project wich work with smarthomeNG

Thanks a lot for your help

**Comment by zobi** [comment]
Sorry maybe a pip problem, i install from setup.py and it work nice ;) 
Thanks a lot for your job ;)
